/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
	"fmt"
)

// Kind the model 'Kind'
type Kind string

// List of kind
const (
	SLO                       Kind = "SLO"
	BUDGET_ADJUSTMENT         Kind = "BudgetAdjustment"
	SLI                       Kind = "SLI"
	SERVICE                   Kind = "Service"
	DATA_SOURCE               Kind = "DataSource"
	ALERT_CONDITION           Kind = "AlertCondition"
	ALERT_POLICY              Kind = "AlertPolicy"
	ALERT_NOTIFICATION_TARGET Kind = "AlertNotificationTarget"
)

// All allowed values of Kind enum
var AllowedKindEnumValues = []Kind{
	"SLO",
	"BudgetAdjustment",
	"SLI",
	"Service",
	"DataSource",
	"AlertCondition",
	"AlertPolicy",
	"AlertNotificationTarget",
}

func (v *Kind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Kind(value)
	for _, existing := range AllowedKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Kind", value)
}

// NewKindFromValue returns a pointer to a valid Kind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewKindFromValue(v string) (*Kind, error) {
	ev := Kind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Kind: valid values are %v", v, AllowedKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Kind) IsValid() bool {
	for _, existing := range AllowedKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to kind value
func (v Kind) Ptr() *Kind {
	return &v
}

type NullableKind struct {
	value *Kind
	isSet bool
}

func (v NullableKind) Get() *Kind {
	return v.value
}

func (v *NullableKind) Set(val *Kind) {
	v.value = val
	v.isSet = true
}

func (v NullableKind) IsSet() bool {
	return v.isSet
}

func (v *NullableKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKind(val *Kind) *NullableKind {
	return &NullableKind{value: val, isSet: true}
}

func (v NullableKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
