/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TimeSliceWindow - struct for TimeSliceWindow
type TimeSliceWindow struct {
	Float32 *float32
	String  *string
}

// float32AsTimeSliceWindow is a convenience function that returns float32 wrapped in TimeSliceWindow
func Float32AsTimeSliceWindow(v *float32) TimeSliceWindow {
	return TimeSliceWindow{
		Float32: v,
	}
}

// stringAsTimeSliceWindow is a convenience function that returns string wrapped in TimeSliceWindow
func StringAsTimeSliceWindow(v *string) TimeSliceWindow {
	return TimeSliceWindow{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *TimeSliceWindow) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Float32
	err = newStrictDecoder(data).Decode(&dst.Float32)
	if err == nil {
		jsonFloat32, _ := json.Marshal(dst.Float32)
		if string(jsonFloat32) == "{}" { // empty struct
			dst.Float32 = nil
		} else {
			if err = validator.Validate(dst.Float32); err != nil {
				dst.Float32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Float32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Float32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TimeSliceWindow)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TimeSliceWindow)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TimeSliceWindow) MarshalJSON() ([]byte, error) {
	if src.Float32 != nil {
		return json.Marshal(&src.Float32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TimeSliceWindow) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Float32 != nil {
		return obj.Float32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableTimeSliceWindow struct {
	value *TimeSliceWindow
	isSet bool
}

func (v NullableTimeSliceWindow) Get() *TimeSliceWindow {
	return v.value
}

func (v *NullableTimeSliceWindow) Set(val *TimeSliceWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableTimeSliceWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableTimeSliceWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTimeSliceWindow(val *TimeSliceWindow) *NullableTimeSliceWindow {
	return &NullableTimeSliceWindow{value: val, isSet: true}
}

func (v NullableTimeSliceWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTimeSliceWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
