/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
	"fmt"
)

// OpensloApiVersion the model 'OpensloApiVersion'
type OpensloApiVersion string

// List of opensloApiVersion
const (
	OPENSLO_V1 OpensloApiVersion = "openslo/v1"
)

// All allowed values of OpensloApiVersion enum
var AllowedOpensloApiVersionEnumValues = []OpensloApiVersion{
	"openslo/v1",
}

func (v *OpensloApiVersion) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OpensloApiVersion(value)
	for _, existing := range AllowedOpensloApiVersionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OpensloApiVersion", value)
}

// NewOpensloApiVersionFromValue returns a pointer to a valid OpensloApiVersion
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOpensloApiVersionFromValue(v string) (*OpensloApiVersion, error) {
	ev := OpensloApiVersion(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OpensloApiVersion: valid values are %v", v, AllowedOpensloApiVersionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OpensloApiVersion) IsValid() bool {
	for _, existing := range AllowedOpensloApiVersionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to opensloApiVersion value
func (v OpensloApiVersion) Ptr() *OpensloApiVersion {
	return &v
}

type NullableOpensloApiVersion struct {
	value *OpensloApiVersion
	isSet bool
}

func (v NullableOpensloApiVersion) Get() *OpensloApiVersion {
	return v.value
}

func (v *NullableOpensloApiVersion) Set(val *OpensloApiVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableOpensloApiVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableOpensloApiVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpensloApiVersion(val *OpensloApiVersion) *NullableOpensloApiVersion {
	return &NullableOpensloApiVersion{value: val, isSet: true}
}

func (v NullableOpensloApiVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpensloApiVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

