/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
)

// checks if the ServiceSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceSpec{}

// ServiceSpec struct for ServiceSpec
type ServiceSpec struct {
	Description *string `json:"description,omitempty"`
}

// NewServiceSpec instantiates a new ServiceSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceSpec() *ServiceSpec {
	this := ServiceSpec{}
	return &this
}

// NewServiceSpecWithDefaults instantiates a new ServiceSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceSpecWithDefaults() *ServiceSpec {
	this := ServiceSpec{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServiceSpec) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceSpec) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServiceSpec) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServiceSpec) SetDescription(v string) {
	o.Description = &v
}

func (o ServiceSpec) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return toSerialize, nil
}

type NullableServiceSpec struct {
	value *ServiceSpec
	isSet bool
}

func (v NullableServiceSpec) Get() *ServiceSpec {
	return v.value
}

func (v *NullableServiceSpec) Set(val *ServiceSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceSpec(val *ServiceSpec) *NullableServiceSpec {
	return &NullableServiceSpec{value: val, isSet: true}
}

func (v NullableServiceSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
