/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AlertPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertPolicy{}

// AlertPolicy struct for AlertPolicy
type AlertPolicy struct {
	ApiVersion OpensloApiVersion `json:"apiVersion"`
	Kind       AlertPolicyKind   `json:"kind"`
	Metadata   Metadata          `json:"metadata"`
	Spec       *AlertPolicySpec  `json:"spec,omitempty"`
}

type _AlertPolicy AlertPolicy

// NewAlertPolicy instantiates a new AlertPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertPolicy(apiVersion OpensloApiVersion, kind AlertPolicyKind, metadata Metadata) *AlertPolicy {
	this := AlertPolicy{}
	this.ApiVersion = apiVersion
	this.Kind = kind
	this.Metadata = metadata
	return &this
}

// NewAlertPolicyWithDefaults instantiates a new AlertPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertPolicyWithDefaults() *AlertPolicy {
	this := AlertPolicy{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *AlertPolicy) GetApiVersion() OpensloApiVersion {
	if o == nil {
		var ret OpensloApiVersion
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *AlertPolicy) GetApiVersionOk() (*OpensloApiVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *AlertPolicy) SetApiVersion(v OpensloApiVersion) {
	o.ApiVersion = v
}

// GetKind returns the Kind field value
func (o *AlertPolicy) GetKind() AlertPolicyKind {
	if o == nil {
		var ret AlertPolicyKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AlertPolicy) GetKindOk() (*AlertPolicyKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AlertPolicy) SetKind(v AlertPolicyKind) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *AlertPolicy) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *AlertPolicy) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *AlertPolicy) SetMetadata(v Metadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *AlertPolicy) GetSpec() AlertPolicySpec {
	if o == nil || IsNil(o.Spec) {
		var ret AlertPolicySpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicy) GetSpecOk() (*AlertPolicySpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *AlertPolicy) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given AlertPolicySpec and assigns it to the Spec field.
func (o *AlertPolicy) SetSpec(v AlertPolicySpec) {
	o.Spec = &v
}

func (o AlertPolicy) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiVersion"] = o.ApiVersion
	toSerialize["kind"] = o.Kind
	toSerialize["metadata"] = o.Metadata
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

func (o *AlertPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiVersion",
		"kind",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertPolicy := _AlertPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlertPolicy)

	if err != nil {
		return err
	}

	*o = AlertPolicy(varAlertPolicy)

	return err
}

type NullableAlertPolicy struct {
	value *AlertPolicy
	isSet bool
}

func (v NullableAlertPolicy) Get() *AlertPolicy {
	return v.value
}

func (v *NullableAlertPolicy) Set(val *AlertPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertPolicy(val *AlertPolicy) *NullableAlertPolicy {
	return &NullableAlertPolicy{value: val, isSet: true}
}

func (v NullableAlertPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
