/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AlertNotificationTarget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertNotificationTarget{}

// AlertNotificationTarget struct for AlertNotificationTarget
type AlertNotificationTarget struct {
	ApiVersion OpensloApiVersion           `json:"apiVersion"`
	Kind       AlertNotificationTargetKind `json:"kind"`
	Metadata   Metadata                    `json:"metadata"`
	Spec       AlertNotificationTargetSpec `json:"spec"`
}

type _AlertNotificationTarget AlertNotificationTarget

// NewAlertNotificationTarget instantiates a new AlertNotificationTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertNotificationTarget(apiVersion OpensloApiVersion, kind AlertNotificationTargetKind, metadata Metadata, spec AlertNotificationTargetSpec) *AlertNotificationTarget {
	this := AlertNotificationTarget{}
	this.ApiVersion = apiVersion
	this.Kind = kind
	this.Metadata = metadata
	this.Spec = spec
	return &this
}

// NewAlertNotificationTargetWithDefaults instantiates a new AlertNotificationTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertNotificationTargetWithDefaults() *AlertNotificationTarget {
	this := AlertNotificationTarget{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *AlertNotificationTarget) GetApiVersion() OpensloApiVersion {
	if o == nil {
		var ret OpensloApiVersion
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *AlertNotificationTarget) GetApiVersionOk() (*OpensloApiVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *AlertNotificationTarget) SetApiVersion(v OpensloApiVersion) {
	o.ApiVersion = v
}

// GetKind returns the Kind field value
func (o *AlertNotificationTarget) GetKind() AlertNotificationTargetKind {
	if o == nil {
		var ret AlertNotificationTargetKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AlertNotificationTarget) GetKindOk() (*AlertNotificationTargetKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AlertNotificationTarget) SetKind(v AlertNotificationTargetKind) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *AlertNotificationTarget) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *AlertNotificationTarget) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *AlertNotificationTarget) SetMetadata(v Metadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value
func (o *AlertNotificationTarget) GetSpec() AlertNotificationTargetSpec {
	if o == nil {
		var ret AlertNotificationTargetSpec
		return ret
	}

	return o.Spec
}

// GetSpecOk returns a tuple with the Spec field value
// and a boolean to check if the value has been set.
func (o *AlertNotificationTarget) GetSpecOk() (*AlertNotificationTargetSpec, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spec, true
}

// SetSpec sets field value
func (o *AlertNotificationTarget) SetSpec(v AlertNotificationTargetSpec) {
	o.Spec = v
}

func (o AlertNotificationTarget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertNotificationTarget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiVersion"] = o.ApiVersion
	toSerialize["kind"] = o.Kind
	toSerialize["metadata"] = o.Metadata
	toSerialize["spec"] = o.Spec
	return toSerialize, nil
}

func (o *AlertNotificationTarget) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiVersion",
		"kind",
		"metadata",
		"spec",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertNotificationTarget := _AlertNotificationTarget{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlertNotificationTarget)

	if err != nil {
		return err
	}

	*o = AlertNotificationTarget(varAlertNotificationTarget)

	return err
}

type NullableAlertNotificationTarget struct {
	value *AlertNotificationTarget
	isSet bool
}

func (v NullableAlertNotificationTarget) Get() *AlertNotificationTarget {
	return v.value
}

func (v *NullableAlertNotificationTarget) Set(val *AlertNotificationTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertNotificationTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertNotificationTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertNotificationTarget(val *AlertNotificationTarget) *NullableAlertNotificationTarget {
	return &NullableAlertNotificationTarget{value: val, isSet: true}
}

func (v NullableAlertNotificationTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertNotificationTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
