/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
)

// checks if the SLIInline type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SLIInline{}

// SLIInline struct for SLIInline
type SLIInline struct {
	Metadata *Metadata `json:"metadata,omitempty"`
	Spec *SliSpec `json:"spec,omitempty"`
}

// NewSLIInline instantiates a new SLIInline object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSLIInline() *SLIInline {
	this := SLIInline{}
	return &this
}

// NewSLIInlineWithDefaults instantiates a new SLIInline object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSLIInlineWithDefaults() *SLIInline {
	this := SLIInline{}
	return &this
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *SLIInline) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SLIInline) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *SLIInline) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *SLIInline) SetMetadata(v Metadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *SLIInline) GetSpec() SliSpec {
	if o == nil || IsNil(o.Spec) {
		var ret SliSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SLIInline) GetSpecOk() (*SliSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *SLIInline) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given SliSpec and assigns it to the Spec field.
func (o *SLIInline) SetSpec(v SliSpec) {
	o.Spec = &v
}

func (o SLIInline) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SLIInline) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableSLIInline struct {
	value *SLIInline
	isSet bool
}

func (v NullableSLIInline) Get() *SLIInline {
	return v.value
}

func (v *NullableSLIInline) Set(val *SLIInline) {
	v.value = val
	v.isSet = true
}

func (v NullableSLIInline) IsSet() bool {
	return v.isSet
}

func (v *NullableSLIInline) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSLIInline(val *SLIInline) *NullableSLIInline {
	return &NullableSLIInline{value: val, isSet: true}
}

func (v NullableSLIInline) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSLIInline) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


