/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AlertPolicyNotificationTarget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertPolicyNotificationTarget{}

// AlertPolicyNotificationTarget struct for AlertPolicyNotificationTarget
type AlertPolicyNotificationTarget struct {
	ApiVersion OpensloApiVersion            `json:"apiVersion"`
	Kind       string                       `json:"kind"`
	Metadata   Metadata                     `json:"metadata"`
	Spec       *AlertNotificationTargetSpec `json:"spec,omitempty"`
	TargetRef  *string                      `json:"targetRef,omitempty" validate:"regexp=^[a-z0-9][a-z0-9.|\\/\\\\\\\\-]*[a-z0-9]*$"`
}

type _AlertPolicyNotificationTarget AlertPolicyNotificationTarget

// NewAlertPolicyNotificationTarget instantiates a new AlertPolicyNotificationTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertPolicyNotificationTarget(apiVersion OpensloApiVersion, kind string, metadata Metadata) *AlertPolicyNotificationTarget {
	this := AlertPolicyNotificationTarget{}
	this.ApiVersion = apiVersion
	this.Kind = kind
	this.Metadata = metadata
	return &this
}

// NewAlertPolicyNotificationTargetWithDefaults instantiates a new AlertPolicyNotificationTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertPolicyNotificationTargetWithDefaults() *AlertPolicyNotificationTarget {
	this := AlertPolicyNotificationTarget{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *AlertPolicyNotificationTarget) GetApiVersion() OpensloApiVersion {
	if o == nil {
		var ret OpensloApiVersion
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *AlertPolicyNotificationTarget) GetApiVersionOk() (*OpensloApiVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *AlertPolicyNotificationTarget) SetApiVersion(v OpensloApiVersion) {
	o.ApiVersion = v
}

// GetKind returns the Kind field value
func (o *AlertPolicyNotificationTarget) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AlertPolicyNotificationTarget) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AlertPolicyNotificationTarget) SetKind(v string) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *AlertPolicyNotificationTarget) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *AlertPolicyNotificationTarget) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *AlertPolicyNotificationTarget) SetMetadata(v Metadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *AlertPolicyNotificationTarget) GetSpec() AlertNotificationTargetSpec {
	if o == nil || IsNil(o.Spec) {
		var ret AlertNotificationTargetSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyNotificationTarget) GetSpecOk() (*AlertNotificationTargetSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *AlertPolicyNotificationTarget) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given AlertNotificationTargetSpec and assigns it to the Spec field.
func (o *AlertPolicyNotificationTarget) SetSpec(v AlertNotificationTargetSpec) {
	o.Spec = &v
}

// GetTargetRef returns the TargetRef field value if set, zero value otherwise.
func (o *AlertPolicyNotificationTarget) GetTargetRef() string {
	if o == nil || IsNil(o.TargetRef) {
		var ret string
		return ret
	}
	return *o.TargetRef
}

// GetTargetRefOk returns a tuple with the TargetRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyNotificationTarget) GetTargetRefOk() (*string, bool) {
	if o == nil || IsNil(o.TargetRef) {
		return nil, false
	}
	return o.TargetRef, true
}

// HasTargetRef returns a boolean if a field has been set.
func (o *AlertPolicyNotificationTarget) HasTargetRef() bool {
	if o != nil && !IsNil(o.TargetRef) {
		return true
	}

	return false
}

// SetTargetRef gets a reference to the given string and assigns it to the TargetRef field.
func (o *AlertPolicyNotificationTarget) SetTargetRef(v string) {
	o.TargetRef = &v
}

func (o AlertPolicyNotificationTarget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertPolicyNotificationTarget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiVersion"] = o.ApiVersion
	toSerialize["kind"] = o.Kind
	toSerialize["metadata"] = o.Metadata
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	if !IsNil(o.TargetRef) {
		toSerialize["targetRef"] = o.TargetRef
	}
	return toSerialize, nil
}

func (o *AlertPolicyNotificationTarget) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiVersion",
		"kind",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertPolicyNotificationTarget := _AlertPolicyNotificationTarget{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlertPolicyNotificationTarget)

	if err != nil {
		return err
	}

	*o = AlertPolicyNotificationTarget(varAlertPolicyNotificationTarget)

	return err
}

type NullableAlertPolicyNotificationTarget struct {
	value *AlertPolicyNotificationTarget
	isSet bool
}

func (v NullableAlertPolicyNotificationTarget) Get() *AlertPolicyNotificationTarget {
	return v.value
}

func (v *NullableAlertPolicyNotificationTarget) Set(val *AlertPolicyNotificationTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertPolicyNotificationTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertPolicyNotificationTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertPolicyNotificationTarget(val *AlertPolicyNotificationTarget) *NullableAlertPolicyNotificationTarget {
	return &NullableAlertPolicyNotificationTarget{value: val, isSet: true}
}

func (v NullableAlertPolicyNotificationTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertPolicyNotificationTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
