/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
)

// checks if the TotalRatioMetric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TotalRatioMetric{}

// TotalRatioMetric struct for TotalRatioMetric
type TotalRatioMetric struct {
	MetricSource *MetricSource `json:"metricSource,omitempty"`
}

// NewTotalRatioMetric instantiates a new TotalRatioMetric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTotalRatioMetric() *TotalRatioMetric {
	this := TotalRatioMetric{}
	return &this
}

// NewTotalRatioMetricWithDefaults instantiates a new TotalRatioMetric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTotalRatioMetricWithDefaults() *TotalRatioMetric {
	this := TotalRatioMetric{}
	return &this
}

// GetMetricSource returns the MetricSource field value if set, zero value otherwise.
func (o *TotalRatioMetric) GetMetricSource() MetricSource {
	if o == nil || IsNil(o.MetricSource) {
		var ret MetricSource
		return ret
	}
	return *o.MetricSource
}

// GetMetricSourceOk returns a tuple with the MetricSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TotalRatioMetric) GetMetricSourceOk() (*MetricSource, bool) {
	if o == nil || IsNil(o.MetricSource) {
		return nil, false
	}
	return o.MetricSource, true
}

// HasMetricSource returns a boolean if a field has been set.
func (o *TotalRatioMetric) HasMetricSource() bool {
	if o != nil && !IsNil(o.MetricSource) {
		return true
	}

	return false
}

// SetMetricSource gets a reference to the given MetricSource and assigns it to the MetricSource field.
func (o *TotalRatioMetric) SetMetricSource(v MetricSource) {
	o.MetricSource = &v
}

func (o TotalRatioMetric) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TotalRatioMetric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MetricSource) {
		toSerialize["metricSource"] = o.MetricSource
	}
	return toSerialize, nil
}

type NullableTotalRatioMetric struct {
	value *TotalRatioMetric
	isSet bool
}

func (v NullableTotalRatioMetric) Get() *TotalRatioMetric {
	return v.value
}

func (v *NullableTotalRatioMetric) Set(val *TotalRatioMetric) {
	v.value = val
	v.isSet = true
}

func (v NullableTotalRatioMetric) IsSet() bool {
	return v.isSet
}

func (v *NullableTotalRatioMetric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTotalRatioMetric(val *TotalRatioMetric) *NullableTotalRatioMetric {
	return &NullableTotalRatioMetric{value: val, isSet: true}
}

func (v NullableTotalRatioMetric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTotalRatioMetric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
