/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AlertPolicyCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertPolicyCondition{}

// AlertPolicyCondition struct for AlertPolicyCondition
type AlertPolicyCondition struct {
	ApiVersion   OpensloApiVersion   `json:"apiVersion"`
	Kind         AlertConditionKind  `json:"kind"`
	Metadata     Metadata            `json:"metadata"`
	Spec         *AlertConditionSpec `json:"spec,omitempty"`
	ConditionRef *string             `json:"conditionRef,omitempty" validate:"regexp=^[a-z0-9][a-z0-9.|\\/\\\\\\\\-]*[a-z0-9]*$"`
}

type _AlertPolicyCondition AlertPolicyCondition

// NewAlertPolicyCondition instantiates a new AlertPolicyCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertPolicyCondition(apiVersion OpensloApiVersion, kind AlertConditionKind, metadata Metadata) *AlertPolicyCondition {
	this := AlertPolicyCondition{}
	this.ApiVersion = apiVersion
	this.Kind = kind
	this.Metadata = metadata
	return &this
}

// NewAlertPolicyConditionWithDefaults instantiates a new AlertPolicyCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertPolicyConditionWithDefaults() *AlertPolicyCondition {
	this := AlertPolicyCondition{}
	return &this
}

// GetApiVersion returns the ApiVersion field value
func (o *AlertPolicyCondition) GetApiVersion() OpensloApiVersion {
	if o == nil {
		var ret OpensloApiVersion
		return ret
	}

	return o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetApiVersionOk() (*OpensloApiVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiVersion, true
}

// SetApiVersion sets field value
func (o *AlertPolicyCondition) SetApiVersion(v OpensloApiVersion) {
	o.ApiVersion = v
}

// GetKind returns the Kind field value
func (o *AlertPolicyCondition) GetKind() AlertConditionKind {
	if o == nil {
		var ret AlertConditionKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetKindOk() (*AlertConditionKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AlertPolicyCondition) SetKind(v AlertConditionKind) {
	o.Kind = v
}

// GetMetadata returns the Metadata field value
func (o *AlertPolicyCondition) GetMetadata() Metadata {
	if o == nil {
		var ret Metadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetMetadataOk() (*Metadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *AlertPolicyCondition) SetMetadata(v Metadata) {
	o.Metadata = v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *AlertPolicyCondition) GetSpec() AlertConditionSpec {
	if o == nil || IsNil(o.Spec) {
		var ret AlertConditionSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetSpecOk() (*AlertConditionSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *AlertPolicyCondition) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given AlertConditionSpec and assigns it to the Spec field.
func (o *AlertPolicyCondition) SetSpec(v AlertConditionSpec) {
	o.Spec = &v
}

// GetConditionRef returns the ConditionRef field value if set, zero value otherwise.
func (o *AlertPolicyCondition) GetConditionRef() string {
	if o == nil || IsNil(o.ConditionRef) {
		var ret string
		return ret
	}
	return *o.ConditionRef
}

// GetConditionRefOk returns a tuple with the ConditionRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetConditionRefOk() (*string, bool) {
	if o == nil || IsNil(o.ConditionRef) {
		return nil, false
	}
	return o.ConditionRef, true
}

// HasConditionRef returns a boolean if a field has been set.
func (o *AlertPolicyCondition) HasConditionRef() bool {
	if o != nil && !IsNil(o.ConditionRef) {
		return true
	}

	return false
}

// SetConditionRef gets a reference to the given string and assigns it to the ConditionRef field.
func (o *AlertPolicyCondition) SetConditionRef(v string) {
	o.ConditionRef = &v
}

func (o AlertPolicyCondition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertPolicyCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiVersion"] = o.ApiVersion
	toSerialize["kind"] = o.Kind
	toSerialize["metadata"] = o.Metadata
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	if !IsNil(o.ConditionRef) {
		toSerialize["conditionRef"] = o.ConditionRef
	}
	return toSerialize, nil
}

func (o *AlertPolicyCondition) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiVersion",
		"kind",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlertPolicyCondition := _AlertPolicyCondition{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlertPolicyCondition)

	if err != nil {
		return err
	}

	*o = AlertPolicyCondition(varAlertPolicyCondition)

	return err
}

type NullableAlertPolicyCondition struct {
	value *AlertPolicyCondition
	isSet bool
}

func (v NullableAlertPolicyCondition) Get() *AlertPolicyCondition {
	return v.value
}

func (v *NullableAlertPolicyCondition) Set(val *AlertPolicyCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertPolicyCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertPolicyCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertPolicyCondition(val *AlertPolicyCondition) *NullableAlertPolicyCondition {
	return &NullableAlertPolicyCondition{value: val, isSet: true}
}

func (v NullableAlertPolicyCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertPolicyCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
