/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
)

// checks if the AlertNotificationTarget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertNotificationTarget{}

// AlertNotificationTarget struct for AlertNotificationTarget
type AlertNotificationTarget struct {
	ApiVersion *OpensloApiVersion           `json:"apiVersion,omitempty"`
	Kind       *string                      `json:"kind,omitempty"`
	Metadata   *Metadata                    `json:"metadata,omitempty"`
	Spec       *AlertNotificationTargetSpec `json:"spec,omitempty"`
}

// NewAlertNotificationTarget instantiates a new AlertNotificationTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertNotificationTarget() *AlertNotificationTarget {
	this := AlertNotificationTarget{}
	return &this
}

// NewAlertNotificationTargetWithDefaults instantiates a new AlertNotificationTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertNotificationTargetWithDefaults() *AlertNotificationTarget {
	this := AlertNotificationTarget{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *AlertNotificationTarget) GetApiVersion() OpensloApiVersion {
	if o == nil || IsNil(o.ApiVersion) {
		var ret OpensloApiVersion
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertNotificationTarget) GetApiVersionOk() (*OpensloApiVersion, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *AlertNotificationTarget) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given OpensloApiVersion and assigns it to the ApiVersion field.
func (o *AlertNotificationTarget) SetApiVersion(v OpensloApiVersion) {
	o.ApiVersion = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *AlertNotificationTarget) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertNotificationTarget) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *AlertNotificationTarget) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *AlertNotificationTarget) SetKind(v string) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AlertNotificationTarget) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertNotificationTarget) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AlertNotificationTarget) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *AlertNotificationTarget) SetMetadata(v Metadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *AlertNotificationTarget) GetSpec() AlertNotificationTargetSpec {
	if o == nil || IsNil(o.Spec) {
		var ret AlertNotificationTargetSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertNotificationTarget) GetSpecOk() (*AlertNotificationTargetSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *AlertNotificationTarget) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given AlertNotificationTargetSpec and assigns it to the Spec field.
func (o *AlertNotificationTarget) SetSpec(v AlertNotificationTargetSpec) {
	o.Spec = &v
}

func (o AlertNotificationTarget) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertNotificationTarget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	return toSerialize, nil
}

type NullableAlertNotificationTarget struct {
	value *AlertNotificationTarget
	isSet bool
}

func (v NullableAlertNotificationTarget) Get() *AlertNotificationTarget {
	return v.value
}

func (v *NullableAlertNotificationTarget) Set(val *AlertNotificationTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertNotificationTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertNotificationTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertNotificationTarget(val *AlertNotificationTarget) *NullableAlertNotificationTarget {
	return &NullableAlertNotificationTarget{value: val, isSet: true}
}

func (v NullableAlertNotificationTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertNotificationTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
