/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
	"fmt"
)

// AlertConditionKind the model 'AlertConditionKind'
type AlertConditionKind string

// List of alertCondition_kind
const (
	ALERT_CONDITION AlertConditionKind = "AlertCondition"
)

// All allowed values of AlertConditionKind enum
var AllowedAlertConditionKindEnumValues = []AlertConditionKind{
	"AlertCondition",
}

func (v *AlertConditionKind) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AlertConditionKind(value)
	for _, existing := range AllowedAlertConditionKindEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AlertConditionKind", value)
}

// NewAlertConditionKindFromValue returns a pointer to a valid AlertConditionKind
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAlertConditionKindFromValue(v string) (*AlertConditionKind, error) {
	ev := AlertConditionKind(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AlertConditionKind: valid values are %v", v, AllowedAlertConditionKindEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AlertConditionKind) IsValid() bool {
	for _, existing := range AllowedAlertConditionKindEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to alertCondition_kind value
func (v AlertConditionKind) Ptr() *AlertConditionKind {
	return &v
}

type NullableAlertConditionKind struct {
	value *AlertConditionKind
	isSet bool
}

func (v NullableAlertConditionKind) Get() *AlertConditionKind {
	return v.value
}

func (v *NullableAlertConditionKind) Set(val *AlertConditionKind) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertConditionKind) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertConditionKind) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertConditionKind(val *AlertConditionKind) *NullableAlertConditionKind {
	return &NullableAlertConditionKind{value: val, isSet: true}
}

func (v NullableAlertConditionKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertConditionKind) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
