/*
OpenSLO V1 Schema

OpenSLO V1 Schema

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openslo_v1

import (
	"encoding/json"
)

// checks if the AlertPolicyCondition type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlertPolicyCondition{}

// AlertPolicyCondition struct for AlertPolicyCondition
type AlertPolicyCondition struct {
	ApiVersion   *OpensloApiVersion  `json:"apiVersion,omitempty"`
	Kind         *string             `json:"kind,omitempty"`
	Metadata     *Metadata           `json:"metadata,omitempty"`
	Spec         *AlertConditionSpec `json:"spec,omitempty"`
	ConditionRef *string             `json:"conditionRef,omitempty" validate:"regexp=^[a-z0-9][a-z0-9.|\\/\\\\\\\\-]*[a-z0-9]*$"`
}

// NewAlertPolicyCondition instantiates a new AlertPolicyCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlertPolicyCondition() *AlertPolicyCondition {
	this := AlertPolicyCondition{}
	return &this
}

// NewAlertPolicyConditionWithDefaults instantiates a new AlertPolicyCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlertPolicyConditionWithDefaults() *AlertPolicyCondition {
	this := AlertPolicyCondition{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *AlertPolicyCondition) GetApiVersion() OpensloApiVersion {
	if o == nil || IsNil(o.ApiVersion) {
		var ret OpensloApiVersion
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetApiVersionOk() (*OpensloApiVersion, bool) {
	if o == nil || IsNil(o.ApiVersion) {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *AlertPolicyCondition) HasApiVersion() bool {
	if o != nil && !IsNil(o.ApiVersion) {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given OpensloApiVersion and assigns it to the ApiVersion field.
func (o *AlertPolicyCondition) SetApiVersion(v OpensloApiVersion) {
	o.ApiVersion = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *AlertPolicyCondition) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *AlertPolicyCondition) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *AlertPolicyCondition) SetKind(v string) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *AlertPolicyCondition) GetMetadata() Metadata {
	if o == nil || IsNil(o.Metadata) {
		var ret Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetMetadataOk() (*Metadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AlertPolicyCondition) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given Metadata and assigns it to the Metadata field.
func (o *AlertPolicyCondition) SetMetadata(v Metadata) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *AlertPolicyCondition) GetSpec() AlertConditionSpec {
	if o == nil || IsNil(o.Spec) {
		var ret AlertConditionSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetSpecOk() (*AlertConditionSpec, bool) {
	if o == nil || IsNil(o.Spec) {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *AlertPolicyCondition) HasSpec() bool {
	if o != nil && !IsNil(o.Spec) {
		return true
	}

	return false
}

// SetSpec gets a reference to the given AlertConditionSpec and assigns it to the Spec field.
func (o *AlertPolicyCondition) SetSpec(v AlertConditionSpec) {
	o.Spec = &v
}

// GetConditionRef returns the ConditionRef field value if set, zero value otherwise.
func (o *AlertPolicyCondition) GetConditionRef() string {
	if o == nil || IsNil(o.ConditionRef) {
		var ret string
		return ret
	}
	return *o.ConditionRef
}

// GetConditionRefOk returns a tuple with the ConditionRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AlertPolicyCondition) GetConditionRefOk() (*string, bool) {
	if o == nil || IsNil(o.ConditionRef) {
		return nil, false
	}
	return o.ConditionRef, true
}

// HasConditionRef returns a boolean if a field has been set.
func (o *AlertPolicyCondition) HasConditionRef() bool {
	if o != nil && !IsNil(o.ConditionRef) {
		return true
	}

	return false
}

// SetConditionRef gets a reference to the given string and assigns it to the ConditionRef field.
func (o *AlertPolicyCondition) SetConditionRef(v string) {
	o.ConditionRef = &v
}

func (o AlertPolicyCondition) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlertPolicyCondition) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiVersion) {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.Spec) {
		toSerialize["spec"] = o.Spec
	}
	if !IsNil(o.ConditionRef) {
		toSerialize["conditionRef"] = o.ConditionRef
	}
	return toSerialize, nil
}

type NullableAlertPolicyCondition struct {
	value *AlertPolicyCondition
	isSet bool
}

func (v NullableAlertPolicyCondition) Get() *AlertPolicyCondition {
	return v.value
}

func (v *NullableAlertPolicyCondition) Set(val *AlertPolicyCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableAlertPolicyCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableAlertPolicyCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlertPolicyCondition(val *AlertPolicyCondition) *NullableAlertPolicyCondition {
	return &NullableAlertPolicyCondition{value: val, isSet: true}
}

func (v NullableAlertPolicyCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlertPolicyCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
